const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    DECREASE_ITEM_QUANTITY: 'DECREASE_ITEM_QUANTITY'
};

export default CartActionTypes;